export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const LOGIN = 'AUTH/LOGIN'
export const LOGOUT = 'AUTH/LOGOUT'
export const UPDATE_USER = 'AUTH/UPDATE_USER'

export const GET_SPACE = 'SPACE/GET_SPACE'
export const SET_IS_OWNER = 'SPACE/SET_IS_OWNER'

export const GET_LEVEL = 'LEVEL/GET_LEVEL'
export const GET_LEVELS = 'LEVEL/GET_LEVELS'

export const GET_POST = 'POST/GET_POST'
export const GET_POSTS = 'POST/GET_POSTS'

export const GET_SUBSCRIPTION = 'SUBSCRIPTION/GET_SUBSCRIPTION'
export const GET_SUBSCRIPTIONS = 'SUBSCRIPTION/GET_SUBSCRIPTIONS'
export const GET_SUBSCRIBERS = 'SUBSCRIPTION/GET_SUBSCRIBERS'